### PR TITLE
Bump branch and runtime to 22.08

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by aaannz** [comment]
Shouldn't this PR be against new 22.08 branch and not 21.08?

It would be nice to have this merged as Idea flatpak already moved to 22.08 branch.

**Comment by anthr76** [comment]
bot build

**Comment by hfiguiere** [comment]
> Shouldn't this PR be against new 22.08 branch and not 21.08?
> 
> It would be nice to have this merged as Idea flatpak already moved to 22.08 branch.

The branch would need to be created manually by someone who can, but having a PR really allow testing it beforehand. And the build failed.

**Comment by anthr76** [comment]
Can someone kick off this build again? It appears to be a transient error?

**Comment by hfiguiere** [comment]
just

bot, build

**Comment by anthr76** [comment]
Hm, I did that here https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/26#issuecomment-1255768072. I guess the bot wasn't in a good mood that day :)

**Comment by hfiguiere** [comment]
this is not a transient error.

**Comment by refi64** [comment]
Looks like two certificates have the same alias but different fingerprints:

```
[📦 org.freedesktop.Platform ~]$ (for cert in /etc/ssl/certs/*.pem; do echo $cert $(openssl x509 -in $cert -noout -sha1 -fingerprint); done) | grep '0B:BE:C2:27:22:49:CB:39:AA:DB:35:5C:53:E3:8C:AE:78:FF:B6:FE\|AE:C5:FB:3F:C8:E1:BF:C4:E5:4F:03:07:5A:9A:E8:00:B7:F7:B6:FA'
/etc/ssl/certs/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem sha1 Fingerprint=AE:C5:FB:3F:C8:E1:BF:C4:E5:4F:03:07:5A:9A:E8:00:B7:F7:B6:FA
/etc/ssl/certs/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068_1.pem sha1 Fingerprint=0B:BE:C2:27:22:49:CB:39:AA:DB:35:5C:53:E3:8C:AE:78:FF:B6:FE
[📦 org.freedesktop.Platform ~]$ 
```

The second of these would appear to be the newer one, comparing to the certificates in runtime 21.08.

**Comment by hfiguiere** [comment]
see #28

**Pull request closed without merging**
