### PR TITLE
Update to 11.0.16.1

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by MatMaul** [comment]
@mbooth101 little up on that, with a similar update also available for 17 LTS.
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk17/pull/6
Thanks !

**Comment by MatMaul** [comment]
@TingPing @barthalion I am not sure who to ping to move this forward, sorry if you can't help.

**Comment by hfiguiere** [comment]
same should be done for the 22.08 branch

**Comment by MatMaul** [comment]
Thnaks ! I've push a PR for 22.08, and there is also 2 PRs for OpenJDK 17 LTS:
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk17/pulls

**Pull request merged**
