### PR TITLE
Build for 1.6

### PR DESCRIPTION
**Pull request by cpba**

### CODE REVIEW

**Comment by barthalion** [comment]
testbot, build

**Comment by barthalion** [comment]
bot, build

**Comment by mbooth101** [comment]
Why is this necessary, can your app not work with freedesktop 18.08?

**Comment by cpba** [comment]
Looks like it won't be needed, after testing it I believe the f-droid
problem may be caused by something else.

Sorry for opening the pull request out of context, we had been talking
about it on irc and I didn't think to write an explanation.

**Comment by mbooth101** [comment]
> Looks like it won't be needed

Okay, thanks for the feedback, I will close this PR accordingly

**Pull request closed without merging**
